name: Waka Readme


on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Waka - Readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.1.5
        with:
          WAKATIME_API_KEY: 9423f1ce-d945-45fc-87d4-25c59d4d6d63
          GH_TOKEN: 6558f964e87627e442f5997f362f94d4696eea1b
